services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_PASS=password
    volumes:
      - ./src/toot47:/app/src/toot47
      - ./data:/app/data
      - chroma_data:/app/chroma_db
      - user_data:/app/data/users
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
  chroma_data:
  user_data: 