version: '3.8'

services:
  neo4j:
    image: neo4j:5.19
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    volumes:
      - ./src:/app/src

volumes:
  neo4j_data: 